name: TDR Run Lambda Tests
on:
  pull_request:
  push:
    branches-ignore:
      - master
      - release-*
permissions:
  id-token: write
  contents: write
jobs:
  test:
    uses: nationalarchives/tdr-github-actions/.github/workflows/tdr_test.yml@f318ce8a5d99c08b1235663f97fdb1b35844674e # v0.0.39
    with:
      repo-name: tdr-consignment-export-authoriser
      test-command: |
        sbt test
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
